require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');
const { Client } = require('pg');

const SUPABASE_URL = process.env.SUPABASE_URL || 'https://lriapvoderqzvecjezpe.supabase.co';
const SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
const DB_PASS = encodeURIComponent(process.env.SUPABASE_DB_PASSWORD || '');
const PROJECT_REF = SUPABASE_URL.match(/https:\/\/(.+?)\.supabase\.co/)?.[1] || 'lriapvoderqzvecjezpe';

if (!SERVICE_KEY || !process.env.SUPABASE_DB_PASSWORD) {
    console.error('ERROR: Missing required environment variables (SUPABASE_SERVICE_KEY, SUPABASE_DB_PASSWORD)');
    process.exit(1);
}

// 1. Create Admin User via Supabase API
async function createAdminUser() {
    console.log('--- Creating Admin User ---');
    const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
        auth: { autoRefreshToken: false, persistSession: false }
    });

    const { data, error } = await supabase.auth.admin.createUser({
        email: process.env.ADMIN_EMAIL || 'admin@example.com',
        password: process.env.ADMIN_PASSWORD || 'change_me',
        email_confirm: true,
        user_metadata: { role: 'admin' }
    });

    if (error) {
        console.error('Error creating user:', error.message);
    } else {
        console.log('User created successfully:', data.user.email);
    }
}

// 2. Create Tables via Postgres Connection (Trying common regions)
async function createTables() {
    console.log('\n--- Creating Database Tables ---');

    // Common regions for Supabase poolers
    const regions = [
        'aws-0-us-east-1', // N. Virginia (Default)
        'aws-0-sa-east-1', // São Paulo
        'aws-0-eu-central-1', // Frankfurt
        'aws-0-ap-southeast-1' // Singapore
    ];

    for (const region of regions) {
        const poolerHost = `${region}.pooler.supabase.com`;
        const connectionString = `postgresql://postgres.${PROJECT_REF}:${DB_PASS}@${poolerHost}:6543/postgres`;

        console.log(`Trying connection to ${poolerHost}...`);

        const client = new Client({ connectionString, connectionTimeoutMillis: 5000 });

        try {
            await client.connect();
            console.log(`Connected to ${poolerHost}! Executing SQL...`);

            await client.query(`
                -- Create Services Table
                CREATE TABLE IF NOT EXISTS public.services (
                    id bigint generated by default as identity primary key,
                    title text not null,
                    description text,
                    icon_name text,
                    link_url text,
                    display_order int default 0,
                    created_at timestamp with time zone default timezone('utc'::text, now()) not null
                );
                
                -- Enable RLS
                ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
                
                -- Policies (Drop first to avoid errors on re-run)
                DROP POLICY IF EXISTS "Public services are viewable by everyone." ON public.services;
                CREATE POLICY "Public services are viewable by everyone." ON public.services FOR SELECT USING (true);
                
                DROP POLICY IF EXISTS "Authenticated users can modify services." ON public.services;
                CREATE POLICY "Authenticated users can modify services." ON public.services FOR ALL USING (auth.role() = 'authenticated');

                -- Settings Table
                CREATE TABLE IF NOT EXISTS public.settings (
                    key text primary key,
                    value text,
                    description text
                );
                ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
                
                DROP POLICY IF EXISTS "Public settings view" ON public.settings;
                CREATE POLICY "Public settings view" ON public.settings FOR SELECT USING (true);
                
                DROP POLICY IF EXISTS "Auth settings modify" ON public.settings;
                CREATE POLICY "Auth settings modify" ON public.settings FOR ALL USING (auth.role() = 'authenticated');
            `);

            console.log('Tables created successfully!');
            await client.end();
            return; // Success, exit function

        } catch (err) {
            console.error(`Failed to connect/execute on ${poolerHost}:`, err.message);
            // Continue to next region
        }
    }

    console.error('Could not connect to database in any common region. Please run SQL manually.');
}

async function runSetup() {
    await createAdminUser();
    await createTables();
}

runSetup();
