-- OMD 2026 Database Schema

-- 1. Services Table (For dynamic service cards)
create table public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  icon_name text, -- e.g. 'rocket_launch' (Material Icons) or 'service.svg' path
  link_url text,
  display_order int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Content Blocks (For editable text on the site)
create table public.content_blocks (
  id bigint generated by default as identity primary key,
  slug text unique not null, -- e.g. 'hero_title', 'mission_text'
  content text not null,
  section text, -- e.g. 'home', 'about'
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Settings (Global configurations)
create table public.settings (
  key text primary key, -- e.g. 'whatsapp_number', 'contact_email'
  value text,
  description text
);

-- 4. Enable Row Level Security (RLS)
alter table public.services enable row level security;
alter table public.content_blocks enable row level security;
alter table public.settings enable row level security;

-- 5. Policies (Public Read, Admin Write)
-- Assume 'anon' role can read everything
create policy "Public services are viewable by everyone."
  on public.services for select
  using ( true );

create policy "Public content is viewable by everyone."
  on public.content_blocks for select
  using ( true );

create policy "Public settings are viewable by everyone."
  on public.settings for select
  using ( true );

-- For writing, we need an authenticated user with admin rights.
-- For simplicity in this starter, we'll allow any authenticated user to write.
-- In production, you'd check for specific user IDs or roles.
create policy "Authenticated users can insert services."
  on public.services for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update services."
  on public.services for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete services."
  on public.services for delete
  using ( auth.role() = 'authenticated' );

-- Policies for content_blocks
create policy "Authenticated users can insert content."
  on public.content_blocks for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update content."
  on public.content_blocks for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete content."
  on public.content_blocks for delete
  using ( auth.role() = 'authenticated' );

-- Policies for settings
create policy "Authenticated users can insert settings."
  on public.settings for insert
  with check ( auth.role() = 'authenticated' );

create policy "Authenticated users can update settings."
  on public.settings for update
  using ( auth.role() = 'authenticated' );

create policy "Authenticated users can delete settings."
  on public.settings for delete
  using ( auth.role() = 'authenticated' );

-- 6. Seed Data (Initial Content)
insert into public.services (title, description, icon_name, link_url, display_order)
values
  ('Diagnóstico Estratégico', 'Análise profunda com IA.', 'analytics', '#diagnostic', 1),
  ('Kit OrganizaNet', 'Sua base digital completa.', 'folder_special', '#services', 2),
  ('Mapa Estratégico', 'O GPS do seu crescimento.', 'map', '#services', 3);
